//
//  Item.swift
//  Newlife
//
//  Created by Giulio Aterno on 10/11/23.
//

import Foundation

struct Item: Hashable {
    let id = UUID()
    let name: String
    let category: String
}

let items: [Item] = [
    Item(name: "Abiti usati", category: "Abbigliamento"),
    Item(name: "Accendini privi di gas", category: "Varie"),
    Item(name: "Acquario", category: "Oggetti per la casa"),
    Item(name: "Agende in carta e/o cartoncino", category: "Cancelleria"),
    Item(name: "Alimenti scaduti", category: "Rifiuti alimentari"),
    Item(name: "Alluminio (vaschette, fogli)", category: "Riciclabili"),
    Item(name: "Apparecchi elettronici (tv, pc, stereo, etc.)", category: "Elettronica"),
    Item(name: "Apriscatole", category: "Varie"),
    Item(name: "Armadi e ante di mobili", category: "Mobili"),
    Item(name: "Asciugacapelli", category: "Elettronica"),
    Item(name: "Aspirapolvere", category: "Elettronica"),
    Item(name: "Asse da stiro", category: "Casa"),
    Item(name: "Assorbenti igienici", category: "Igiene personale"),
    Item(name: "Attrezzi sportivi grandi (vogatore, cyclette, ecc.)", category: "Sport"),
    Item(name: "Avanzi di cibo", category: "Rifiuti alimentari"),
    Item(name: "Bacinelle", category: "Cucina"),
    Item(name: "Bambole e giocattoli piccoli di stoffa o peluches", category: "Giocattoli"),
    Item(name: "Bancomat, carte di credito, carte fedeltà", category: "Varie"),
    Item(name: "Barattoli rigidi in plastica", category: "Riciclabili"),
    Item(name: "Barattoli in vetro", category: "Riciclabili"),
    Item(name: "Barbecue", category: "Elettronica"),
    Item(name: "Bastoncini per orecchie in plastica e cotone", category: "Igiene personale"),
    Item(name: "Bastoncini per orecchie in carta e cotone", category: "Igiene personale"),
    Item(name: "Batterie (di auto o cellulari)", category: "Riciclabili"),
    Item(name: "Batterie per piccoli elettrodomestici (stilo, ministilo, bottone)", category: "Riciclabili"),
    Item(name: "Batuffoli di cotone", category: "Igiene personale"),
    Item(name: "Bicchieri in cristallo", category: "Cucina"),
    Item(name: "Bicchieri in plastica", category: "Riciclabili"),
    Item(name: "Biciclette", category: "Sport"),
    Item(name: "Bidone (plastica/metallo)", category: "Riciclabili"),
    Item(name: "Bigiotteria", category: "Accessori"),
    Item(name: "Bilance (per alimenti, pesa persone)", category: "Elettronica"),
    Item(name: "Biro e penne a sfera", category: "Cancelleria"),
    Item(name: "Blister di lenti a contatto vuoti", category: "Varie"),
    Item(name: "Blister di pastiglie vuoti", category: "Varie"),
    Item(name: "Bombola del gas", category: "Casa"),
    Item(name: "Bombolette spray vuote", category: "Varie"),
    Item(name: "Borse in pelle/tela/nylon", category: "Accessori"),
    Item(name: "Bottiglie in plastica e flaconi", category: "Riciclabili"),
    Item(name: "Bottiglie in vetro senza tappo", category: "Riciclabili"),
    Item(name: "Bottoni", category: "Cucito"),
    Item(name: "Box per bambini", category: "Arredamento"),
    Item(name: "Box doccia", category: "Arredamento"),
    Item(name: "Brandina", category: "Arredamento"),
    Item(name: "Brick del latte o dei succhi di frutta etc.", category: "Riciclabili"),
    Item(name: "Bucce e scarti di frutta", category: "Rifiuti alimentari"),
    Item(name: "Bullonerie (viti, chiodi, etc.)", category: "Utensili"),
    Item(name: "Buste di carta", category: "Cancelleria"),
    Item(name: "Buste di plastica", category: "Riciclabili"),
    Item(name: "Caffè (resti di preparazione)", category: "Cucina"),
    Item(name: "Calamite", category: "Varie"),
    Item(name: "Caldaia per riscaldamento", category: "Casa"),
    Item(name: "Canalina per acqua o elettricità", category: "Casa"),
    Item(name: "Carne (avanzi di)", category: "Rifiuti alimentari"),
    Item(name: "Carriola", category: "Giardino"),
    Item(name: "Carrozzine e passeggini", category: "Bambini"),
    Item(name: "Carta assorbente per cucina", category: "Cucina"),
    Item(name: "Carta chimica (scontrini, fogli autoricalcanti, etc.)", category: "Cancelleria"),
    Item(name: "Carta da forno", category: "Cucina"),
    Item(name: "Carta da pacchi", category: "Cancelleria"),
    Item(name: "Carta lucida da disegno", category: "Cancelleria"),
    Item(name: "Carta non unta né bagnata", category: "Riciclabili"),
    Item(name: "Carta per alimenti (formaggi o affettati)", category: "Cucina"),
    Item(name: "Carta plastificata", category: "Riciclabili"),
    Item(name: "Carta/cartone sporchi di cibo (es. cartoni pizza)", category: "Riciclabili"),
    Item(name: "Carta velina", category: "Cancelleria"),
    Item(name: "Carte di credito, carte fedeltà", category: "Varie"),
    Item(name: "Cartoni ondulati", category: "Riciclabili"),
    Item(name: "Cartoni per bevande (es. in tetrapak)", category: "Riciclabili"),
    Item(name: "Casco (per moto, bicicletta, etc.)", category: "Sport"),
    Item(name: "Cassapanca", category: "Arredamento"),
    Item(name: "Cassette audio e video (inclusa custodia di plastica rigida)", category: "Elettronica"),
    Item(name: "Cassette della frutta in cartone (spezzettate)", category: "Riciclabili"),
    Item(name: "Cassette della frutta in legno (spezzettate)", category: "Riciclabili"),
    Item(name: "Cassette della frutta in plastica", category: "Riciclabili"),
    Item(name: "Cavi elettrici", category: "Elettronica"),
    Item(name: "Cd (inclusa la custodia di plastica rigida)", category: "Elettronica"),
    Item(name: "Cellulare e caricabatterie", category: "Elettronica"),
    Item(name: "Ceneri del camino o della stufa a pellet", category: "Casa"),
    Item(name: "Ceneri e cicche di sigarette", category: "Varie"),
    Item(name: "Ceramiche", category: "Casa"),
    Item(name: "Cerchioni di pneumatici", category: "Veicoli"),
    Item(name: "Cerotti", category: "Pronto soccorso"),
    Item(name: "Cialde in plastica per caffè espresso", category: "Cucina"),
    Item(name: "Cialde in carta per caffè espresso", category: "Cucina"),
    Item(name: "Cibi (avanzi sia cotti che crudi)", category: "Rifiuti alimentari"),
    Item(name: "Collant", category: "Abbigliamento"),
    Item(name: "Computer e componenti (tastiera, mouse, etc.)", category: "Elettronica"),
    Item(name: "Condizionatori d’aria", category: "Elettronica"),
    Item(name: "Confezioni del caffè", category: "Cucina"),
    Item(name: "Confezioni in carta (di merendine, zucchero, etc.)", category: "Cucina"),
    Item(name: "Contenitori di detersivi e cosmetici in plastica", category: "Igiene personale"),
    Item(name: "Contenitori di prodotti per l’igiene personale", category: "Igiene personale"),
    Item(name: "Coperchi in plastica", category: "Cucina"),
    Item(name: "Coperchi in stagnola di vasetti yogurt", category: "Cucina"),
    Item(name: "Coperte", category: "Casa"),
    Item(name: "Cornici di qualsiasi materiale", category: "Casa"),
    Item(name: "Cosmetici (contenitori pieni)", category: "Igiene personale"),
    Item(name: "Cosmetici (contenitori vuoti)", category: "Igiene personale"),
    Item(name: "Cristalli (bicchieri, caraffe e oggetti vari)", category: "Casa"),
    Item(name: "Cuscini", category: "Casa"),
    Item(name: "Damigiane in vetro", category: "Cucina"),
    Item(name: "Depliant in carta", category: "Cancelleria"),
    Item(name: "Divani", category: "Arredamento"),
    Item(name: "Dvd (inclusa la custodia di plastica rigida)", category: "Elettronica"),
    Item(name: "Elettrodomestici grandi (lavatrici, frigoriferi, ecc.)", category: "Elettronica"),
    Item(name: "Elettrodomestici piccoli (frullatori, tostapane, phone, ecc.)", category: "Elettronica"),
    Item(name: "Escrementi animali (lettiere)", category: "Animali domestici"),
    Item(name: "Faldoni in cartone (senza anelli)", category: "Cancelleria"),
    Item(name: "Farmaci scaduti", category: "Pronto soccorso"),
    Item(name: "Fasciatoio", category: "Bambini"),
    Item(name: "Fax (carta chimica)", category: "Elettronica"),
    Item(name: "Fax (macchina)", category: "Elettronica"),
    Item(name: "Ferri da stiro", category: "Casa"),
    Item(name: "Flaconi in plastica per detersivo", category: "Igiene personale"),
    Item(name: "Flaconi in plastica di prodotti per l’igiene personale", category: "Igiene personale"),
    Item(name: "Floppy disk", category: "Elettronica"),
    Item(name: "Foglie e fiori", category: "Giardino"),
    Item(name: "Fondi di tè, caffè, camomilla", category: "Cucina"),
    Item(name: "Formaggi e salumi", category: "Cucina"),
    Item(name: "Forni (elettrici, microonde, etc.)", category: "Elettronica"),
    Item(name: "Fotocopiatrice", category: "Elettronica"),
    Item(name: "Fotografie e pellicole fotografiche", category: "Fotografia"),
    Item(name: "Frigoriferi", category: "Elettronica"),
    Item(name: "Frutta (avanzi, bucce)", category: "Rifiuti alimentari"),
    Item(name: "Giocattoli in plastica e/o elettrici", category: "Giocattoli"),
    Item(name: "Giocattoli piccoli in stoffa o peluche", category: "Giocattoli"),
    Item(name: "Giornali e riviste", category: "Cancelleria"),
    Item(name: "Gommapiuma", category: "Casa"),
    Item(name: "Graffette e fermagli", category: "Cancelleria"),
    Item(name: "Grucce e appendiabiti in plastica", category: "Casa"),
    Item(name: "Grucce e appendiabiti in legno", category: "Casa"),
    Item(name: "Guanti monouso", category: "Igiene personale"),
    Item(name: "Gusci d’uova", category: "Rifiuti alimentari"),
    Item(name: "Gusci di molluschi", category: "Rifiuti alimentari"),
    Item(name: "Infissi", category: "Materiali edili"),
    Item(name: "Ingombranti (mobili, reti, materassi, elettrodomestici, etc.)", category: "Rifiuti ingombranti"),
    Item(name: "Lampadari", category: "Illuminazione"),
    Item(name: "Lampade al neon, fluorescenti e a LED", category: "Rifiuti elettronici"),
    Item(name: "Lampadine a incandescenza e alogene", category: "Rifiuti elettronici"),
    Item(name: "Lattine per bevande e per olio", category: "Riciclabili"),
    Item(name: "Lavatrici e lavastoviglie", category: "Elettrodomestici"),
    Item(name: "Lavello/Lavabo", category: "Elettrodomestici"),
    Item(name: "Legno da potatura da utenza domestica", category: "Rifiuti verdi"),
    Item(name: "Lettiere di animali domestici", category: "Rifiuti domestici"),
    Item(name: "Libri", category: "Carta e cartone"),
    Item(name: "Macchina da cucire", category: "Elettrodomestici"),
    Item(name: "Macchina del gas (senza bombola)", category: "Elettrodomestici"),
    Item(name: "Mascherine monouso", category: "Rifiuti speciali"),
    Item(name: "Materassi", category: "Rifiuti ingombranti"),
    Item(name: "Materassi gonfiabili", category: "Rifiuti ingombranti"),
    Item(name: "Matite", category: "Varie"),
    Item(name: "Mensole e scaffali", category: "Arredamento"),
    Item(name: "Mobilio", category: "Arredamento"),
    Item(name: "Mollette per il bucato", category: "Varie"),
    Item(name: "Moquettes", category: "Rifiuti ingombranti"),
    Item(name: "Mozziconi di sigarette e sigari", category: "Rifiuti speciali"),
    Item(name: "Nastro (adesivo, da imballaggio)", category: "Varie"),
    Item(name: "Neon", category: "Rifiuti elettronici"),
    Item(name: "Noccioli della frutta", category: "Rifiuti organici"),
    Item(name: "Occhiali", category: "Varie"),
    Item(name: "Olio vegetale (usi alimentari)", category: "Rifiuti speciali"),
    Item(name: "Olio per motori", category: "Rifiuti speciali"),
    Item(name: "Ombrelli", category: "Varie"),
    Item(name: "Ombrelloni", category: "Varie"),
    Item(name: "Orologi (da muro, da polso, etc.)", category: "Varie"),
    Item(name: "Ossi (animali)", category: "Rifiuti organici"),
    Item(name: "Ovatta", category: "Varie"),
    Item(name: "Pallet", category: "Materiali edili"),
    Item(name: "Pane e pasta", category: "Alimenti"),
    Item(name: "Pannolini e pannoloni", category: "Rifiuti speciali"),
    Item(name: "Pellicole di cellophane", category: "Rifiuti plastici"),
    Item(name: "Peluche", category: "Giocattoli"),
    Item(name: "Penne e pennarelli", category: "Carta e cartone"),
    Item(name: "Pesce", category: "Rifiuti organici"),
    Item(name: "Pentole e padelle", category: "Utensili da cucina"),
    Item(name: "Pettini in plastica", category: "Prodotti per la cura personale"),
    Item(name: "Pettini in legno", category: "Prodotti per la cura personale"),
    Item(name: "Piatti di bambù o cartoncino", category: "Carta e cartone"),
    Item(name: "Piatti di plastica (senza residui alimentari)", category: "Plastica"),
    Item(name: "Piatti in ceramica e porcellana", category: "Ceramica e porcellana"),
    Item(name: "Pile scariche", category: "Rifiuti speciali"),
    Item(name: "Polistirolo (per alimenti e imballaggi)", category: "Rifiuti plastici"),
    Item(name: "Poltrone", category: "Arredamento"),
    Item(name: "Posate di bambù", category: "Utensili da cucina"),
    Item(name: "Posate di metallo", category: "Utensili da cucina"),
    Item(name: "Posate di plastica", category: "Plastica"),
    Item(name: "Quaderni", category: "Carta e cartone"),
    Item(name: "Quadri (di qualsiasi materiale)", category: "Arte e artigianato"),
    Item(name: "Ramaglie e residui da giardino da utenza domestica", category: "Rifiuti verdi"),
    Item(name: "Rete da letto", category: "Rifiuti ingombranti"),
    Item(name: "Riviste", category: "Carta e cartone"),
    Item(name: "Rubinetterie", category: "Rifiuti metallici"),
    Item(name: "Sacchetti, buste e tabulati di carta", category: "Carta e cartone"),
    Item(name: "Sacchetti dell’aspirapolvere", category: "Varie"),
    Item(name: "Sacchetti di plastica", category: "Rifiuti plastici"),
    Item(name: "Scaffali", category: "Arredamento"),
    Item(name: "Scarpe e scarponi", category: "Abbigliamento e calzature"),
    Item(name: "Scarti di cibo (crudo o cotto)", category: "Rifiuti organici"),
    Item(name: "Scatole di cartone e cartoncino", category: "Carta e cartone"),
    Item(name: "Scatolette di pomodoro, tonno, etc.", category: "Rifiuti metallici"),
    Item(name: "Schede magnetiche (bancomat, carte di credito, etc.)", category: "Rifiuti elettronici"),
    Item(name: "Sci", category: "Attrezzature sportive"),
    Item(name: "Scontrini fiscali e fatture carta chimica", category: "Carta e cartone"),
    Item(name: "Sedie", category: "Arredamento"),
    Item(name: "Seggiolino per auto", category: "Bambini e neonati"),
    Item(name: "Sfalci da giardini/prati/potatura da utenza domestica", category: "Rifiuti verdi"),
    Item(name: "Siringhe (con ago bene ricoperto)", category: "Rifiuti speciali"),
    Item(name: "Spazzole per capelli o per abiti", category: "Prodotti per la cura personale"),
    Item(name: "Spazzolini da denti in plastica", category: "Prodotti per la cura personale"),
    Item(name: "Spazzolini da denti in bambù", category: "Prodotti per la cura personale"),
    Item(name: "Specchi di grandi dimensioni", category: "Arredamento"),
    Item(name: "Specchi di piccole dimensioni", category: "Arredamento"),
    Item(name: "Spillatrici", category: "Ufficio"),
    Item(name: "Spugne sintetiche", category: "Prodotti per la cura personale"),
    Item(name: "Stampanti, privi di toner o cartucce", category: "Rifiuti elettronici"),
    Item(name: "Stendiabiti", category: "Arredamento"),
    Item(name: "Stereo (impianti o parti)", category: "Elettronica"),
    Item(name: "Stoffe in genere", category: "Abbigliamento e tessuti"),
    Item(name: "Stracci puliti", category: "Varie"),
    Item(name: "Strumenti musicali grandi (batteria, chitarra, ecc.)", category: "Strumenti musicali"),
    Item(name: "Strumenti musicali piccoli (flauto, ecc.)", category: "Strumenti musicali"),
    Item(name: "Stufa (di qualsiasi tipo)", category: "Elettrodomestici"),
    Item(name: "Tamponi per timbri", category: "Ufficio"),
    Item(name: "Tappeti (di piccole dimensioni), tendaggi e tappezzerie", category: "Arredamento"),
    Item(name: "Tappeti (di medie e grandi dimensioni)", category: "Arredamento"),
    Item(name: "Tappezzerie", category: "Arredamento"),
    Item(name: "Tappi in metalli", category: "Rifiuti metallici"),
    Item(name: "Tappi in plastica", category: "Rifiuti plastici"),
    Item(name: "Tappi in sughero", category: "Varie"),
    Item(name: "Tazzine in ceramica e porcellana", category: "Ceramica e porcellana"),
    Item(name: "Telaio di porta/finestra", category: "Materiali edili"),
    Item(name: "Telefoni", category: "Elettronica"),
    Item(name: "Televisori, telecomandi privi di batterie", category: "Elettronica"),
    Item(name: "Tende", category: "Arredamento"),
    Item(name: "Termosifoni", category: "Elettrodomestici"),
    Item(name: "Tetrapak (es. cartone del latte)", category: "Rifiuti plastici"),
    Item(name: "Toner (da utenza domestica)", category: "Rifiuti speciali"),
    Item(name: "Torsoli di frutta", category: "Rifiuti organici"),
    Item(name: "Tovaglioli di carta sporchi", category: "Rifiuti organici"),
    Item(name: "Tubetti di dentifricio", category: "Rifiuti speciali"),
    Item(name: "Utensilerie piccole (cacciavite, pinza, etc.)", category: "Utensili"),
    Item(name: "Valigie", category: "Bagagli"),
    Item(name: "Vaschette per alimenti in plastica", category: "Plastica"),
    Item(name: "Vasetti dello yogurt", category: "Plastica"),
    Item(name: "Vasetti di vetro", category: "Vetro"),
    Item(name: "Vasi da vivaisti in plastica morbida", category: "Plastica"),
    Item(name: "Vasi in plastica rigida, ceramica, terracotta, cristallo", category: "Plastica e ceramica"),
    Item(name: "Ventilatori da tavolo", category: "Elettrodomestici"),
    Item(name: "Ventilatori di grandi dimensioni e a piantana", category: "Elettrodomestici"),
    Item(name: "Vernici", category: "Rifiuti speciali"),
    Item(name: "Vestiario (abiti e accessori)", category: "Abbigliamento"),
    Item(name: "Vetri da serramenti o rotti o in lastre", category: "Vetro"),
    Item(name: "Videocassette", category: "Rifiuti elettronici"),
    Item(name: "Videoregistratori", category: "Rifiuti elettronici"),
    Item(name: "Volantini e pieghevoli pubblicitari", category: "Carta e cartone"),
    Item(name: "Wi-fi", category: "Elettronica"),
    Item(name: "Zaini", category: "Borse e zaini"),
    Item(name: "Zanzariere", category: "Arredamento"),
    Item(name: "Zerbini (piccole dimensioni)", category: "Arredamento")
]




